version: "3.8"

services:

  postgres:
    hostname: postgres
    image: postgres:14
    environment:
    - POSTGRES_USER=user
    - POSTGRES_DB=cluster_manager
    - POSTGRES_PASSWORD=password
    ports:
    - 5432
    healthcheck:
      test:
      - CMD
      - psql
      - -U
      - user
      - -d
      - cluster_manager
      - pg_isready
      interval: 1s
      timeout: 10s
      retries: 10
    networks:
    - cluster-manager

  server:
    hostname: server
    build:
      context: .
      dockerfile: ./build/server/Dockerfile
    command:
    - run
    - --config
    - /etc/config/config.yaml
    environment:
      DB_PASSWORD: password
    ports:
    - 8080:8080
    - 8081:8081
    - 8082:8082
    volumes:
    - ./configs/server:/etc/config
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
    - cluster-manager

networks:
  cluster-manager:
