{{- if .Values.defaultCluster.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: default-cluster-registration-key
  labels:
    {{- include "cluster-manager-server.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ .Values.defaultCluster.registrationKey | b64enc }}
{{- end -}}
