httpPort: 8080
grpcPort: 8081
workerServiceGrpcPort: 8082
internalGrpcPort: 8083

database:
  host: postgres
  port: 5432
  database: cluster_manager
  username: user
  passwordEnvName: DB_PASSWORD

defaultCluster:
  name: Default
  registrationKey: default-cluster-registration-key-secret
  tenantId: default-tenant-id
