global:
  database:
    host:
    port:
    username:

  databaseSecret:
    name:
    key:

  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:

  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  auth:
    enable:
    rbacInternalServerAddr:

httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8082

database:
  database: cluster_manager

defaultCluster:
  name: Default
  registrationKey: default-cluster-registration-key-secret
  tenantId: default-tenant-id

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/cluster-manager-server
  pullPolicy: IfNotPresent

version:
